#!/bin/bash

# Delete previous coverage reports and test results
rm -rf ./CoverageReport
find . -type d -name "TestResults" -exec rm -rf {} +

export REPORTGENERATOR_LICENSE=ewogICJMaWNlbnNlIjogewogICAgIklkIjogIjc5MGU2OGM1LTU1NTktNDdiZi1hOWUxLTM4OTRhNzcyZGU0OSIsCiAgICAiTG9naW4iOiAiNzkwZTY4YzUtNTU1OS00N2JmLWE5ZTEtMzg5NGE3NzJkZTQ5IiwKICAgICJOYW1lIjogIk1hdG91cyIsCiAgICAiRW1haWwiOiAic2FnZWYxNjA2NUBoYXpoYWIuY29tIiwKICAgICJMaWNlbnNlVHlwZSI6ICJUcmlhbCIsCiAgICAiSXNzdWVkQXQiOiAiMjAyNS0wNS0xNFQxNTowNDozNi45OTYzMDQ2WiIsCiAgICAiRXhwaXJlc0F0IjogIjIwMjUtMDUtMjVUMDA6MDA6MDBaIgogIH0sCiAgIlNpZ25hdHVyZSI6ICJ0RzBiT3laT3VCRzB5MnNBUEx4U3NiQUJGeXFCcy9Hc0tHbTA0NlpBcFhSTXN0OGtacHdhS1N1UmJyTzdHZkxFNjlERjVwV2w4QVVwQXRteHpcdTAwMkJrUW90bzhXQWFXYm9MNDdPaFB3Y0x5S3pzSTF4ZGFIZW16cGFQOHFMWVpqdnh6WGpWZlBMa3ZCZmZPOS8yd3ZxR2N0SkhmaG1KVnQwN0EyVmhpT2ZXdkRwN0c1Rmh5WE5FL3VXdThKbTR2U0hvc1JpY3F0dnlINmJKVTI2YU5tQlQxaDRwTEE0cnJsSG5pY2d6Zm84Q29wVHRpQkFweTBVQThpNjFYamFHVmZtbmxHQTNUZmN2c3FGYlNWa1dcdTAwMkJyeWd1TnptRHdCT2J2VHlJMFVNVTdBQzVcdTAwMkJVWDR4dU1qbXJMYnhXY2ozL1Fxcmw0R2ZIR1d2TG5MNU5TTmE5bkNqVUxXdnc9PSIKfQ==

# Run the tests with coverage collection using runsettings file
dotnet test --settings:coverlet.runsettings --collect:"XPlat Code Coverage" --filter "Category!=Integration" --verbosity:normal

# Generate the report with filters to exclude specific files
dotnet reportgenerator \
  -reports:"**/TestResults/**/coverage.cobertura.xml" \
  -targetdir:"CoverageReport" \
  -reporttypes:Html \
  -filefilters:"-**/Deprecated_CustomerOrderProcessor.cs;-**/Deprecated_CustomerOrderProcessorTests.cs;-**/Microsoft.NET.Test.Sdk.Program.cs;-**/*Program.cs;-**/*OrderProcessingMessages.Designer.cs" \
  -classfilters:"-*.AutoGeneratedProgram" \
  -verbosity:Info
