//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactoringChallenge.Orchestration.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderProcessingMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderProcessingMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactoringChallenge.Orchestration.Resources.OrderProcessingMessages", typeof(OrderProcessingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer ID must be a positive number..
        /// </summary>
        internal static string CustomerIdMustBePositive
        {
            get
            {
                return ResourceManager.GetString("CustomerIdMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found customer: {0} (VIP: {1}).
        /// </summary>
        internal static string CustomerFound
        {
            get
            {
                return ResourceManager.GetString("CustomerFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer not found with ID: {0}.
        /// </summary>
        internal static string CustomerNotFoundError
        {
            get
            {
                return ResourceManager.GetString("CustomerNotFoundError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer with ID {0} not found..
        /// </summary>
        internal static string CustomerNotFoundException
        {
            get
            {
                return ResourceManager.GetString("CustomerNotFoundException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid customer ID: {0}.
        /// </summary>
        internal static string InvalidCustomerId
        {
            get
            {
                return ResourceManager.GetString("InvalidCustomerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product ID {0} has insufficient inventory. Required: {1}, Available: {2}.
        /// </summary>
        internal static string InsufficientInventory
        {
            get
            {
                return ResourceManager.GetString("InsufficientInventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated inventory for product ID {0}, reduced by {1}.
        /// </summary>
        internal static string InventoryUpdated
        {
            get
            {
                return ResourceManager.GetString("InventoryUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order completed with {0}% discount. Total price: {1}.
        /// </summary>
        internal static string OrderCompletedLog
        {
            get
            {
                return ResourceManager.GetString("OrderCompletedLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order {0} is on hold due to insufficient inventory.
        /// </summary>
        internal static string OrderOnHold
        {
            get
            {
                return ResourceManager.GetString("OrderOnHold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order on hold. Some items are not on stock..
        /// </summary>
        internal static string OrderOnHoldLog
        {
            get
            {
                return ResourceManager.GetString("OrderOnHoldLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order {0} processed with {1}% discount. Final amount: {2}.
        /// </summary>
        internal static string OrderProcessedWithDiscount
        {
            get
            {
                return ResourceManager.GetString("OrderProcessedWithDiscount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order {0} raw total amount: {1}.
        /// </summary>
        internal static string OrderRawTotal
        {
            get
            {
                return ResourceManager.GetString("OrderRawTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order {0} is ready for shipping.
        /// </summary>
        internal static string OrderReady
        {
            get
            {
                return ResourceManager.GetString("OrderReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated order {0} with processed status and discounts.
        /// </summary>
        internal static string OrderUpdated
        {
            get
            {
                return ResourceManager.GetString("OrderUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed processing {0} orders for customer ID: {1}.
        /// </summary>
        internal static string OrdersProcessingCompleted
        {
            get
            {
                return ResourceManager.GetString("OrdersProcessingCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} pending orders for customer ID: {1}.
        /// </summary>
        internal static string PendingOrdersFound
        {
            get
            {
                return ResourceManager.GetString("PendingOrdersFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing order ID: {0}.
        /// </summary>
        internal static string ProcessingOrderId
        {
            get
            {
                return ResourceManager.GetString("ProcessingOrderId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting to process orders for customer ID: {0}.
        /// </summary>
        internal static string StartingProcessCustomerOrders
        {
            get
            {
                return ResourceManager.GetString("StartingProcessCustomerOrders", resourceCulture);
            }
        }
    }
}
